//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWallet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int Id { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int BankAccountId { get; set; }
        public int ExpenseCategoryId { get; set; }
        public decimal Ammount { get; set; }
        public string Comment { get; set; }
        public long UserId { get; set; }
        public decimal NewBallance { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual ExpenseCategory ExpenseCategory { get; set; }
        public virtual User User { get; set; }
    }
}
